sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yasir6403/dock-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yasir6403/dock-react npm run test